# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
workspace '../PopupViewController'

target 'Example' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Cartography', :git => 'https://github.com/solomon23/Cartography.git', :branch => '3.0'

end
