# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
workspace '../PopupViewController'

target 'PopupViewController' do
  use_frameworks!
  pod 'Cartography'
end

target 'PopupViewControllerTests' do
  use_frameworks!
  pod 'Cartography'
end
