# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
workspace '../PopupViewController'

target 'PopupViewController' do
  use_frameworks!
  pod 'Cartography', :git => 'https://github.com/solomon23/Cartography.git', :branch => '3.0'
end

target 'PopupViewControllerTests' do
  use_frameworks!
  pod 'Cartography', :git => 'https://github.com/solomon23/Cartography.git', :branch => '3.0'
end
